"""ORM models. Importing this package registers every table on ``Base.metadata``."""

from app.models.community import (
    Comment,
    FeedPreference,
    Follow,
    Like,
    MarketCache,
    Media,
    Post,
    PostReport,
    RateEvent,
    Save,
    TopicFollow,
    User,
    UserSession,
)
from app.models.connectivity import (
    Account,
    ApiKey,
    AuditLog,
    CompanyProfile,
    Connection,
    EconomicObservation,
    EconomicSeries,
    Fundamental,
    Holding,
    ImportBatch,
    SourceRecord,
    SyncRun,
    Transaction,
    WebhookDelivery,
    WebhookEndpoint,
)
from app.models.market import Asset, DataQualityIssue, DataQualityRun, Dataset, IngestionRun, MarketData
from app.models.ops import Job, Notification, Report
from app.models.portfolio import Portfolio, PortfolioPosition, PortfolioReturn, RiskMetric, StressTest
from app.models.research import (
    Anomaly,
    Backtest,
    BacktestTrade,
    Experiment,
    ExperimentMetric,
    MLPrediction,
    Strategy,
)

__all__ = [
    "Account",
    "Anomaly",
    "ApiKey",
    "Asset",
    "AuditLog",
    "Backtest",
    "BacktestTrade",
    "Comment",
    "CompanyProfile",
    "Connection",
    "DataQualityIssue",
    "DataQualityRun",
    "Dataset",
    "EconomicObservation",
    "EconomicSeries",
    "Experiment",
    "ExperimentMetric",
    "FeedPreference",
    "Follow",
    "Fundamental",
    "Holding",
    "ImportBatch",
    "IngestionRun",
    "Job",
    "Like",
    "MLPrediction",
    "MarketCache",
    "MarketData",
    "Media",
    "Notification",
    "Portfolio",
    "PortfolioPosition",
    "PortfolioReturn",
    "Post",
    "PostReport",
    "RateEvent",
    "Report",
    "RiskMetric",
    "Save",
    "SourceRecord",
    "Strategy",
    "StressTest",
    "SyncRun",
    "TopicFollow",
    "Transaction",
    "User",
    "UserSession",
    "WebhookDelivery",
    "WebhookEndpoint",
]
