"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 00:10:36.128842
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('code', name=op.f('uq_datasets_code'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_status', ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_read_created', ['is_read', 'created_at'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('key', name=op.f('uq_strategies_key'))
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('is_benchmark', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_assets_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('dataset_id', 'symbol', name='uq_assets_dataset_symbol')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('data_quality_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(length=80), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('per_symbol', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_data_quality_runs_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_runs'))
    )
    with op.batch_alter_table('data_quality_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_runs_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('experiment_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(length=80), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('train_start', sa.Date(), nullable=True),
    sa.Column('train_end', sa.Date(), nullable=True),
    sa.Column('test_start', sa.Date(), nullable=True),
    sa.Column('test_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('reproducibility', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_experiments_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['experiments.id'], name=op.f('fk_experiments_parent_id_experiments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments')),
    sa.UniqueConstraint('code', name=op.f('uq_experiments_code'))
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index('ix_experiments_type_created', ['experiment_type', 'created_at'], unique=False)

    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('requested_start', sa.Date(), nullable=True),
    sa.Column('requested_end', sa.Date(), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('records_skipped_existing', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(length=80), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_ingestion_runs_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_runs_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_symbol', sa.String(length=32), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('rebalance_frequency', sa.String(length=16), nullable=False),
    sa.Column('allocation_method', sa.String(length=32), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('allocation_details', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_portfolios_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    sa.UniqueConstraint('name', name=op.f('uq_portfolios_name'))
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('top_feature', sa.String(length=64), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('matches_injected_event', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_anomalies_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomalies'))
    )
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.create_index('ix_anomalies_exp_score', ['experiment_id', 'score'], unique=False)

    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strategy_key', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_symbol', sa.String(length=32), nullable=True),
    sa.Column('execution', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('series', sa.JSON(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_backtests_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_backtests_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtests')),
    sa.UniqueConstraint('experiment_id', name=op.f('uq_backtests_experiment_id'))
    )
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('dq_run_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('check', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_data_quality_issues_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dq_run_id'], ['data_quality_runs.id'], name=op.f('fk_data_quality_issues_dq_run_id_data_quality_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_data_quality_issues_ingestion_run_id_ingestion_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_issues'))
    )
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.create_index('ix_dq_issues_dataset_check', ['dataset_id', 'check'], unique=False)

    op.create_table('experiment_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_metrics_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_metrics'))
    )
    with op.batch_alter_table('experiment_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_experiment_metrics_exp', ['experiment_id'], unique=False)

    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_market_data_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_market_data_ingestion_run_id_ingestion_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data')),
    sa.UniqueConstraint('asset_id', 'date', name='uq_market_data_asset_date')
    )
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.create_index('ix_market_data_date', ['date'], unique=False)

    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('split', sa.String(length=16), nullable=False),
    sa.Column('y_true', sa.Float(), nullable=True),
    sa.Column('y_pred', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_ml_predictions_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_predictions'))
    )
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.create_index('ix_ml_predictions_exp_model', ['experiment_id', 'model'], unique=False)

    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_positions_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_positions')),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_positions_portfolio_symbol')
    )
    op.create_table('portfolio_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_returns_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_returns')),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_portfolio_returns_portfolio_date')
    )
    op.create_table('risk_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('var', sa.Float(), nullable=False),
    sa.Column('cvar', sa.Float(), nullable=True),
    sa.Column('var_amount', sa.Float(), nullable=True),
    sa.Column('cvar_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_risk_metrics_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_metrics'))
    )
    with op.batch_alter_table('risk_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_metrics_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('stress_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('scenario_type', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('portfolio_impact_pct', sa.Float(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_stress_tests_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stress_tests'))
    )
    with op.batch_alter_table('stress_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stress_tests_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('notional', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('weight_before', sa.Float(), nullable=False),
    sa.Column('weight_after', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], name=op.f('fk_backtest_trades_backtest_id_backtests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_trades'))
    )
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_trades_bt_date', ['backtest_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_backtest_trades_bt_date')

    op.drop_table('backtest_trades')
    with op.batch_alter_table('stress_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stress_tests_portfolio_id'))

    op.drop_table('stress_tests')
    with op.batch_alter_table('risk_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_metrics_portfolio_id'))

    op.drop_table('risk_metrics')
    op.drop_table('portfolio_returns')
    op.drop_table('portfolio_positions')
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_ml_predictions_exp_model')

    op.drop_table('ml_predictions')
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_index('ix_market_data_date')

    op.drop_table('market_data')
    with op.batch_alter_table('experiment_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_experiment_metrics_exp')

    op.drop_table('experiment_metrics')
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.drop_index('ix_dq_issues_dataset_check')

    op.drop_table('data_quality_issues')
    op.drop_table('backtests')
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_index('ix_anomalies_exp_score')

    op.drop_table('anomalies')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_dataset_id'))

    op.drop_table('portfolios')
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_dataset_id'))

    op.drop_table('ingestion_runs')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index('ix_experiments_type_created')

    op.drop_table('experiments')
    with op.batch_alter_table('data_quality_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_runs_dataset_id'))

    op.drop_table('data_quality_runs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_dataset_id'))

    op.drop_table('assets')
    op.drop_table('strategies')
    op.drop_table('reports')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_read_created')

    op.drop_table('notifications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status')

    op.drop_table('jobs')
    op.drop_table('datasets')
    # ### end Alembic commands ###
