"""accounts with email and oauth, news pages, saves, topic follows, feed preferences

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 16:03:11.453102
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feed_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_preferences')),
    sa.UniqueConstraint('user_id', 'key', name='uq_feed_preferences_user_key')
    )
    with op.batch_alter_table('feed_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('topic_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_topic_follows_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_follows')),
    sa.UniqueConstraint('user_id', 'kind', 'value', name='uq_topic_follows_user_kind_value')
    )
    with op.batch_alter_table('topic_follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_follows_user_id'), ['user_id'], unique=False)

    op.create_table('saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_saves_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saves_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saves')),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_saves_post_user')
    )
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saves_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saves_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_url', sa.String(length=1500), nullable=True))
        batch_op.add_column(sa.Column('link_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('link_source', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('link_image', sa.String(length=1500), nullable=True))
        batch_op.add_column(sa.Column('external_key', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_posts_external_key'), ['external_key'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=False, server_default='password'))
        batch_op.add_column(sa.Column('provider_sub', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kind', sa.String(length=12), nullable=False, server_default='person'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_provider_sub'), ['provider_sub'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_provider_sub'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('kind')
        batch_op.drop_column('provider_sub')
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('email')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_posts_external_key'), type_='unique')
        batch_op.drop_column('external_key')
        batch_op.drop_column('link_image')
        batch_op.drop_column('link_source')
        batch_op.drop_column('link_title')
        batch_op.drop_column('link_url')

    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saves_user_id'))
        batch_op.drop_index(batch_op.f('ix_saves_post_id'))

    op.drop_table('saves')
    with op.batch_alter_table('topic_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_follows_user_id'))

    op.drop_table('topic_follows')
    with op.batch_alter_table('feed_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_preferences_user_id'))

    op.drop_table('feed_preferences')
    # ### end Alembic commands ###
