import { useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Change, fmtPrice, SymbolSearch, useMe } from "../components/market";
import { useT } from "../i18n";
import { api, errorMessage } from "../services/api";
import type { AnyObj } from "../types/api";

const SOURCE_LABEL: Record<string, string> = { reddit: "Reddit", x: "X", stocktwits: "StockTwits" };
const OPEN_ON: Record<string, string> = { reddit: "Open on Reddit", x: "Open on X", stocktwits: "Open on StockTwits" };
const PICKS = ["EMAAR.AE", "FAB.AD", "ALDAR.AD", "EMIRATESNBD.AE", "NVDA", "TSLA", "AAPL", "BTC-USD"];

function ago(iso: string | null | undefined, lang: string): string {
  if (!iso) return "";
  const s = (Date.now() - new Date(iso).getTime()) / 1000;
  const rtf = new Intl.RelativeTimeFormat(lang, { numeric: "auto", style: "short" });
  if (s < 3600) return rtf.format(-Math.max(1, Math.floor(s / 60)), "minute");
  if (s < 86400) return rtf.format(-Math.floor(s / 3600), "hour");
  return rtf.format(-Math.floor(s / 86400), "day");
}

function SourceMark({ source }: { source: string }) {
  return <span className={`src-mark ${source}`} aria-hidden>{source === "reddit" ? "r/" : source === "x" ? "𝕏" : "$"}</span>;
}

/** Superscript citation numbers that jump to the post they refer to. */
function Refs({ refs, ids }: { refs: number[]; ids: string[] }) {
  if (!refs.length) return null;
  return (
    <span className="refs">
      {refs.map((n) => (
        <a key={n} href={`#p-${ids[n - 1]}`} onClick={(e) => {
          e.preventDefault();
          const el = document.getElementById(`p-${ids[n - 1]}`);
          if (!el) return;
          el.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth", block: "center" });
          el.classList.remove("flash"); void el.offsetWidth; el.classList.add("flash");
        }}>{n}</a>
      ))}
    </span>
  );
}

function Synthesis({ symbol, total }: { symbol: string; total: number }) {
  const { t } = useT();
  const q = useQuery({ queryKey: ["pulse-ai", symbol], queryFn: () => api.get<AnyObj>(`/pulse/${encodeURIComponent(symbol)}/synthesis`), staleTime: 15 * 60_000, retry: 0 });
  const s = q.data;
  return (
    <section className="ps-syn" aria-busy={q.isLoading}>
      <div className="sec-head">
        <h2>{t("What investors are saying")}</h2>
        <span className="sec-sub">{s?.available ? `${t("AI summary of")} ${s.posts_used} ${t("posts")}${s.model ? ` · ${String(s.model).replace(/^\w+\//, "")}` : ""}` : t("AI summary")}</span>
      </div>
      {q.isLoading && (
        <div className="ps-reading"><span className="rs-busy" aria-hidden /> {t("Reading")} {Math.min(total, 50)} {t("posts and summarising the arguments…")}</div>
      )}
      {q.isError && <div className="hm-error">{errorMessage(q.error)}</div>}
      {s && !s.available && <p className="ps-none">{t("No AI summary")} — {s.reason}</p>}
      {s?.available && (
        <>
          <p className="ps-summary" dir="auto">{s.summary}</p>
          {s.coverage && <p className="hm-fine">{s.coverage}</p>}
          {s.themes.length > 0 && (
            <ol className="ps-themes">
              {s.themes.map((th: AnyObj, i: number) => (
                <li key={i}><b dir="auto">{th.title}</b> <span dir="auto">{th.text}</span><Refs refs={th.refs} ids={s.ref_ids} /></li>
              ))}
            </ol>
          )}
          <div className="ps-sides">
            {([["bull", t("Arguments for")], ["bear", t("Arguments against and risks")], ["questions", t("Open questions")]] as const).map(([k, label]) => (
              <div key={k} className={`ps-side ${k}`}>
                <div className="ps-side-h">{label}</div>
                {(s[k] as AnyObj[]).length ? (
                  <ul>{(s[k] as AnyObj[]).map((p, i) => <li key={i} dir="auto">{p.text}<Refs refs={p.refs} ids={s.ref_ids} /></li>)}</ul>
                ) : <div className="ps-empty">{t("None raised in these posts.")}</div>}
              </div>
            ))}
          </div>
          <p className="hm-fine">{t("Generated by AI from the posts below and cited by number. It describes opinions; it does not check whether they are true.")}</p>
        </>
      )}
    </section>
  );
}

function PostRow({ p, n, symbol }: { p: AnyObj; n: number | null; symbol: string }) {
  const { t, lang } = useT();
  const discuss = `$${symbol} ${p.title ? `"${p.title}"` : ""}\n\n${p.source === "reddit" ? "u/" : "@"}${p.author} on ${SOURCE_LABEL[p.source]}: ${p.url}\n\n`;
  return (
    <li id={`p-${p.id}`} className="ps-post">
      <div className="ps-post-head">
        {n !== null && <span className="ps-n num" title={t("Cited in the summary")}>{n}</span>}
        <SourceMark source={p.source} />
        <a className="ps-author" href={p.author_url} target="_blank" rel="noreferrer noopener" title={`${t("Open")} ${p.author} ${t("on")} ${SOURCE_LABEL[p.source]}`}>
          {p.source === "reddit" ? "u/" : "@"}{p.author}
        </a>
        {p.community && <span className="ps-meta">{p.community}</span>}
        <span className="ps-meta">{SOURCE_LABEL[p.source]}</span>
        <time className="ps-meta" dateTime={p.created_at}>{ago(p.created_at, lang)}</time>
        {p.tag && <span className={`ps-tag ${p.tag.toLowerCase()}`} title={t("Chosen by the poster on StockTwits")}>{t(p.tag)}</span>}
      </div>
      {p.title && <a className="ps-title" href={p.url} target="_blank" rel="noreferrer noopener" dir="auto">{p.title}</a>}
      {p.text && <p className="ps-text" dir="auto">{p.text}</p>}
      <div className="ps-actions">
        {p.score !== null && p.score !== undefined && <span className="ps-meta num">{p.score.toLocaleString()} {p.source === "reddit" ? t("points") : t("likes")}</span>}
        {p.replies !== null && p.replies !== undefined && <span className="ps-meta num">{p.replies.toLocaleString()} {t("replies")}</span>}
        <a href={p.url} target="_blank" rel="noreferrer noopener">{t(OPEN_ON[p.source])} ↗</a>
        <Link to={`/finstagram?compose=${encodeURIComponent(discuss)}`}>{t("Discuss on Nexis")}</Link>
      </div>
    </li>
  );
}

function SourcesBar({ d }: { d: AnyObj }) {
  const { t } = useT();
  const tagged = d.tags.bullish + d.tags.bearish;
  return (
    <div className="ps-sources">
      {Object.entries(d.sources as Record<string, AnyObj>).map(([k, v]) => (
        <div key={k} className={`ps-src ${v.ok ? "ok" : "off"}`}>
          <span className="ps-src-name"><SourceMark source={k} />{SOURCE_LABEL[k]}</span>
          <span className="ps-src-v num">{v.ok ? v.count : "—"}</span>
          <span className="ps-src-note">{v.ok ? `${t("posts collected")} · ${v.via}` : v.error}</span>
        </div>
      ))}
      <div className="ps-src tags">
        <span className="ps-src-name">{t("Self-tagged on StockTwits")}</span>
        {tagged ? (
          <>
            <span className="ps-tagbar" aria-label={`${d.tags.bullish} Bullish, ${d.tags.bearish} Bearish`}>
              <span className="b" style={{ flexGrow: d.tags.bullish }} /><span className="s" style={{ flexGrow: d.tags.bearish }} />
            </span>
            <span className="ps-src-note num">{d.tags.bullish} {t("Bullish")} · {d.tags.bearish} {t("Bearish")} · {tagged} {t("of")} {d.items.filter((i: AnyObj) => i.source === "stocktwits").length} {t("posts tagged")}</span>
          </>
        ) : <span className="ps-src-note">{t("No self-tagged posts")}</span>}
      </div>
    </div>
  );
}

function LinkPrompt() {
  const { t } = useT();
  const me = useMe().data?.user;
  const linked: AnyObj[] = me?.linked ?? [];
  if (me && linked.length >= 2) return null;
  return (
    <aside className="ps-link">
      <b>{t("On Reddit or X?")}</b>
      <span>{t("Link your account so people on Nexis can see who you are when you post and comment.")}</span>
      <Link to={me ? "/settings#linked" : "/login?mode=signup&next=/settings"} className="sec-link">{me ? t("Link accounts") : t("Create an account")} <span aria-hidden>→</span></Link>
    </aside>
  );
}

function AssetPulse({ symbol }: { symbol: string }) {
  const { t } = useT();
  const nav = useNavigate();
  const [filter, setFilter] = useState<"all" | "reddit" | "x" | "stocktwits">("all");
  const q = useQuery({ queryKey: ["pulse", symbol], queryFn: () => api.get<AnyObj>(`/pulse/${encodeURIComponent(symbol)}`), staleTime: 5 * 60_000 });
  const syn = useQuery({ queryKey: ["pulse-ai", symbol], queryFn: () => api.get<AnyObj>(`/pulse/${encodeURIComponent(symbol)}/synthesis`), enabled: false });
  const d = q.data;
  const refNo = useMemo(() => Object.fromEntries(((syn.data?.ref_ids ?? []) as string[]).map((id, i) => [id, i + 1])), [syn.data]);
  const items: AnyObj[] = (d?.items ?? []).filter((i: AnyObj) => filter === "all" || i.source === filter);
  const quote = d?.quote;
  return (
    <div className="hm ps">
      <header className="ps-head">
        <div className="hm-eyebrow"><Link to="/pulse">{t("Nexis Pulse")}</Link><span>{t("Investor opinions from Reddit, X and StockTwits")}</span></div>
        <div className="ps-title-row">
          <h1 dir="auto">{d?.name ?? symbol} <span className="mono ps-tk">{symbol}</span></h1>
          {quote?.price !== null && quote?.price !== undefined && (
            <span className="ps-quote"><span className="num">{fmtPrice(quote.price)}</span> <span className="wl-ccy">{quote.currency}</span> <Change pct={quote.change_pct} /></span>
          )}
          <Link className="sec-link" to={`/markets/${encodeURIComponent(symbol)}`}>{t("Prices, fundamentals and news")} <span aria-hidden>→</span></Link>
        </div>
        <div className="ps-search"><SymbolSearch compact placeholder={t("Another stock, bond or crypto…")} onPick={(s) => nav(`/pulse/${encodeURIComponent(s.symbol)}`)} /></div>
        <p className="ps-warning">{t("These are opinions from public social media, not verified information. A lot of positive or negative talk is not evidence that a price will move.")}</p>
      </header>

      {q.isLoading && <div className="ps-reading"><span className="rs-busy" aria-hidden /> {t("Collecting posts from Reddit, X and StockTwits…")}</div>}
      {q.isError && <div className="hm-error">{errorMessage(q.error)} <button className="link-btn" onClick={() => q.refetch()}>{t("Retry")}</button></div>}
      {d && (
        <>
          <SourcesBar d={d} />
          <div className="ps-grid">
            <div>
              {d.items.length > 0 ? <Synthesis symbol={symbol} total={d.items.length} /> : (
                <section className="ps-syn"><div className="sec-head"><h2>{t("What investors are saying")}</h2></div>
                  <p className="ps-none">{t("No posts about this asset were found on the connected sources right now.")}</p></section>
              )}
              <section className="ps-feed">
                <div className="sec-head">
                  <h2>{t("Posts")}</h2>
                  <span className="sec-sub">{t("Newest first · searched for")} {d.search_terms.map((x: string) => `“${x}”`).join(", ")}</span>
                </div>
                <div className="ps-filters" role="tablist">
                  {(["all", "reddit", "x", "stocktwits"] as const).map((f) => {
                    const n = f === "all" ? d.items.length : d.items.filter((i: AnyObj) => i.source === f).length;
                    return <button key={f} role="tab" aria-selected={filter === f} className={filter === f ? "on" : ""} onClick={() => setFilter(f)}>{f === "all" ? t("All") : SOURCE_LABEL[f]} <span className="num">{n}</span></button>;
                  })}
                </div>
                <ol className="ps-posts">{items.map((p) => <PostRow key={p.id} p={p} n={refNo[p.id] ?? null} symbol={symbol} />)}</ol>
                {!items.length && <div className="hm-empty">{t("Nothing from this source.")}</div>}
              </section>
            </div>
            <aside className="ps-aside">
              <LinkPrompt />
              <div className="ps-about">
                <div className="ps-side-h">{t("How this works")}</div>
                <p>{t("Nexis searches each source for the ticker and the company name, keeps posts that are about the asset, and links every post and author to the original. Counts are a sample of recent posts, not total discussion volume.")}</p>
                <p className="hm-fine">{t("Collected")} {ago(d.fetched_at, "en")} · {t("refreshes every 10 minutes")}</p>
              </div>
            </aside>
          </div>
          <footer className="hm-foot">{d.disclaimer}</footer>
        </>
      )}
    </div>
  );
}

function PulseHome() {
  const { t } = useT();
  const nav = useNavigate();
  const status = useQuery({ queryKey: ["pulse-sources"], queryFn: () => api.get<AnyObj>("/pulse/sources"), staleTime: 600_000 });
  const trending = useQuery({ queryKey: ["social", "trending"], queryFn: () => api.get<AnyObj>("/social/trending"), staleTime: 300_000 });
  const hot: string[] = (trending.data?.symbols ?? []).slice(0, 6).map((s: AnyObj) => s.symbol);
  const picks = [...new Set([...PICKS, ...hot])];
  return (
    <div className="hm ps">
      <header className="ps-head">
        <div className="hm-eyebrow"><span>{t("Nexis Pulse")}</span></div>
        <h1>{t("What are investors saying?")}</h1>
        <p className="hm-lede">{t("Pick a stock, bond or crypto to read the latest public posts about it from Reddit, X and StockTwits, with an AI summary of the arguments on each side. Every post links to the original and its author.")}</p>
        <div className="ps-search wide"><SymbolSearch placeholder={t("Search a stock, bond or crypto…")} onPick={(s) => nav(`/pulse/${encodeURIComponent(s.symbol)}`)} /></div>
      </header>
      <section>
        <div className="sec-head"><h2>{t("Start with")}</h2><span className="sec-sub">{t("UAE favourites and what Finstagram is talking about")}</span></div>
        <div className="ps-picks">
          {picks.map((s) => <Link key={s} className="ps-pick mono" to={`/pulse/${encodeURIComponent(s)}`}>{s}</Link>)}
        </div>
      </section>
      <section className="ps-status">
        <div className="sec-head"><h2>{t("Sources")}</h2></div>
        <ul>
          {Object.entries((status.data?.sources ?? {}) as Record<string, AnyObj>).map(([k, v]) => (
            <li key={k}>
              <span className="ps-src-name"><SourceMark source={k} />{v.label}</span>
              <span className="ps-meta">
                {k === "reddit" && (v.official ? t("Official Reddit API") : v.pending ? t("Waiting for Reddit to approve API access — Reddit posts appear once approved") : t("Reddit's public search feed"))}
                {k === "x" && (v.official ? t("X API") : t("Not connected yet — reading X needs an X API plan"))}
                {k === "stocktwits" && t("Public stream · US-listed stocks and crypto")}
              </span>
            </li>
          ))}
        </ul>
        <p className="hm-fine">{status.data?.disclaimer}</p>
      </section>
      <LinkPrompt />
    </div>
  );
}

export default function Pulse() {
  const { symbol } = useParams();
  return symbol ? <AssetPulse key={symbol} symbol={decodeURIComponent(symbol).toUpperCase()} /> : <PulseHome />;
}
